### ISSUE TITLE
Index error after selecting dub/sub

### ISSUE THREAD

**Issue by ejsch03** [Waxes27/anime-downloader#1]
```
 What anime do you want to download: naruto
1. English(Dub) 
2. Japanese(Sub)
(1./2.) > 2
https://www12.9anime.to/watch/naruto.xx8z
https://www12.9anime.to/watch/naruto.xx8z
Description:


Moments prior to Naruto Uzumaki&#039;s birth, a huge demon known as the Kyuubi, the Nine-Tailed Fox, attacked Konohagakure, the Hidden Leaf Village, and wreaked havoc. In order to put an end to the Kyuubi&#039;s rampage, the leader of the village, the Fourth Hokage, sacrificed his life and sealed the monstrous beast inside the newborn Naruto. Now, Naruto is a hyperactive and knuckle-headed ninja still living in Konohagakure. Shunned because of the Kyuubi inside him, Naruto struggles to find his place in the village, while his burning desire to become the Hokage of Konohagakure leads him not only to some great new friends, but also some deadly foes.


Traceback (most recent call last):
  File "C:\Users\evand\Documents\Programming\Code\Python\Test\z_3.py", line 72, in <module>
    main()
  File "C:\Users\evand\Documents\Programming\Code\Python\Test\z_3.py", line 66, in main
    content = requests.get(list_of_anime[i]).text
IndexError: list index out of range
```
Also, how are you going to go about downloading from 9anime.to?

**Comment by Waxes27** [comment]
Not sure as of yet if I can isolate the video I can download it with ease, I really dont want to use Selenium though but i'll sort out your issue now

**Comment by Waxes27** [comment]
Seems as though I would just need to update the to the latest version

**Comment by ejsch03** [comment]
@Waxes27 Would you like to work on a downloader together?  We could fork our ideas together and practice the use of Github as a collaborative project.  I've already worked on one myself but I'm running out of ideas for improvement. [Here][1] is my version of an anime downloader based from 9anime.to :)

[1]: https://github.com/Daemitrious/9anime_dl

**Comment by Waxes27** [comment]
We can go ahead with the 9anime idea, My ideas were to not use selenium as
much as possible but to implement it as a command line interface to
minimize latency. I took this approach because I did run some tests on
different computers and some ran slower than others plus internet
connectivity is not the same for us all, so I think the best bet would be a
CLI

**Comment by ejsch03** [comment]
Ok sounds good.  The reason for why I use selenium is because I couldn't
grab the total amount of episodes for an anime and I also couldn't grab the
required key in order to post for the direct download link for the
specified episode(s).  I will push push what I have rn, its basically
finished.  The version that I use rn is for Linux and it works as intended,
but it's quite slow because it uses selenium twice and the host limits
download rates to 1 megabyte/s.  It's more of an idle downloader because as
it begins downloading, it goes into the background.   U kinda just leave it
on lol.  But I've downloaded 110 episodes at a time.
